// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type AddAchievementsArgs = {
  "achievements": unknown;
};

export type AddAchievementsReturns = {
  "id": string;
}[];

export async function addAchievements(client: Executor, args: AddAchievementsArgs): Promise<AddAchievementsReturns> {
  return client.query(`\
for key in json_array_unpack(<json>$achievements) union (
  insert Achievement {
    key := <str>key,
  }
)`, args);

}
