// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type GetAchievementsReturns = string[];

export async function getAchievements(client: Executor): Promise<GetAchievementsReturns> {
  return client.query(`\
select (
  select Achievement
  filter .user = global currentUser
).key`);

}
