// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type GetFishesArgs = {
  "category": string;
};

export type GetFishesReturns = {
  "item": string;
  "quantity": number;
}[];

export async function getFishes(client: Executor, args: GetFishesArgs): Promise<GetFishesReturns> {
  return client.query(`\
with item := (
  select Item
  filter .owner = global currentUser
  and .category = <str>$category
),
grouped := (group item by .key)
select grouped {
  item := .key.key,
  quantity := count(.elements),
}`, args);

}
