services:
  pg:
    image: postgres:17beta3-alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      TZ: ${TZ}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
  app:
    depends_on:
      - pg
    image: ghcr.io/tnraro/april-paradise:main
    restart: unless-stopped
    environment:
      PUBLIC_FORM_URL: ${PUBLIC_FORM_URL}
      SHEETS_CLIENT_EMAIL: ${SHEETS_CLIENT_EMAIL}
      SHEETS_PRIVATE_KEY: ${SHEETS_PRIVATE_KEY}
      SHEETS_ID: ${SHEETS_ID}
      SHEETS_URL: ${SHEETS_URL}
      KEY: ${KEY}
      IV: ${IV}
      PUBLIC_SENTRY_DSN: ${PUBLIC_SENTRY_DSN}
      PG_URL: postgres://postgres:${POSTGRES_PASSWORD}@pg:5432/postgres
    ports:
      - ${PORT}:3000

volumes:
  pg: