// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type AddResourceArgs = {
  "key": string;
  "value": number;
};

export type AddResourceReturns = {
  "id": string;
};

export async function addResource(client: Executor, args: AddResourceArgs): Promise<AddResourceReturns> {
  return client.queryRequiredSingle(`\
insert Resource {
  key := <str>$key,
  value := max({ 0, <int64>$value }),
}
unless conflict on (.owner, .key)
else (
  update Resource
  set {
    value := .value + <int64>$value,
  }
)`, args);

}
