// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type AddChipsByCurrentUserArgs = {
  "chips": number;
};

export type AddChipsByCurrentUserReturns = {
  "id": string;
} | null;

export async function addChipsByCurrentUser(client: Executor, args: AddChipsByCurrentUserArgs): Promise<AddChipsByCurrentUserReturns> {
  return client.querySingle(`\
with user := global currentUser
update user
set {
  chips := user.chips + <int64>$chips
}`, args);

}
