// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type AddTokensByCurrentUserArgs = {
  "tokens": number;
};

export type AddTokensByCurrentUserReturns = {
  "id": string;
} | null;

export async function addTokensByCurrentUser(client: Executor, args: AddTokensByCurrentUserArgs): Promise<AddTokensByCurrentUserReturns> {
  return client.querySingle(`\
with user := global currentUser
update user
set {
  tokens := user.tokens + <int64>$tokens
}`, args);

}
