// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type PutArgs = {
  "runners": unknown;
};

export type PutReturns = {
  "id": string;
}[];

export async function put(client: Executor, args: PutArgs): Promise<PutReturns> {
  return client.query(`\
with runners := <json>$runners
for runner in json_array_unpack(runners) union (
  insert User {
    key := <str>runner["key"],
    identity := {}
  }
  unless conflict on .key
)`, args);

}
