// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type LayoutReturns = {
  "id": string;
  "key": string;
} | null;

export async function layout(client: Executor): Promise<LayoutReturns> {
  return client.querySingle(`\
select global currentUser { id, key } filter .isAdmin;`);

}
