// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type QueryDataArgs = {
  "sheet": string;
};

export type QueryDataReturns = {
  "data": string;
} | null;

export async function queryData(client: Executor, args: QueryDataArgs): Promise<QueryDataReturns> {
  return client.querySingle(`\
select StaticData {
  data,
} filter .sheet = <str>$sheet`, args);

}
