// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type LayoutReturns = {
  "id": string;
  "key": string;
}[];

export async function layout(client: Executor): Promise<LayoutReturns> {
  return client.query(`\
select User {
  id,
  key,
} filter not .isAdmin`);

}
