// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type PageArgs = {
  "key": string;
};

export type PageReturns = {
  "key": string;
  "id": string;
  "chips": number;
  "tokens": number;
  "hasIdentity": boolean;
} | null;

export async function page(client: Executor, args: PageArgs): Promise<PageReturns> {
  return client.querySingle(`\
select User {
  key,
  id,
  chips,
  tokens,
  hasIdentity := exists .identity
}
filter .key = <str>$key and not .isAdmin`, args);

}
