// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type AchievementsReturns = {
  "key": string;
  "createdAt": Date;
}[];

export async function achievements(client: Executor): Promise<AchievementsReturns> {
  return client.query(`\
select Achievement {
  key,
  createdAt,
} filter .user = global currentUser;`);

}
