// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type BowlArgs = {
  "category": string;
};

export type BowlReturns = {
  "item": string;
  "quantity": number;
}[];

export async function bowl(client: Executor, args: BowlArgs): Promise<BowlReturns> {
  return client.query(`\
with item := (
  select Item
  filter .owner = global currentUser and .category = <str>$category
),
grouped := (group item by .key)
select grouped {
  item := .key.key,
  quantity := count(.elements)
}`, args);

}
