// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type LuresReturns = {
  "lure0": number;
  "lure1": number;
  "lure2": number;
};

export async function lures(client: Executor): Promise<LuresReturns> {
  return client.queryRequiredSingle(`\
with resources := (
  select Resource
  filter .owner = global currentUser
)
select {
  lure0 := assert_single((select resources filter .key = '까만 콩 지렁이')).value ?? 0,
  lure1 := assert_single((select resources filter .key = '토깽이 떡밥')).value ?? 0,
  lure2 := assert_single((select resources filter .key = '사우루숭 벌레 유충')).value ?? 0,
}`);

}
