// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type AddTicketItemArgs = {
  "key": string;
};

export type AddTicketItemReturns = {
  "id": string;
};

export async function addTicketItem(client: Executor, args: AddTicketItemArgs): Promise<AddTicketItemReturns> {
  return client.queryRequiredSingle(`\
insert Item {
  key := <str>$key,
  category := "ticket",
}`, args);

}
