// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type AddIngredientItemArgs = {
  "key": string;
};

export type AddIngredientItemReturns = {
  "id": string;
};

export async function addIngredientItem(client: Executor, args: AddIngredientItemArgs): Promise<AddIngredientItemReturns> {
  return client.queryRequiredSingle(`\
insert Item {
  key := <str>$key,
  category := "ingredient",
}`, args);

}
