// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type AddGarbageItemArgs = {
  "key": string;
};

export type AddGarbageItemReturns = {
  "id": string;
};

export async function addGarbageItem(client: Executor, args: AddGarbageItemArgs): Promise<AddGarbageItemReturns> {
  return client.queryRequiredSingle(`\
insert Item {
  key := <str>$key,
  category := "garbage",
}`, args);

}
