// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type AddFishItemArgs = {
  "key": string;
};

export type AddFishItemReturns = {
  "id": string;
};

export async function addFishItem(client: Executor, args: AddFishItemArgs): Promise<AddFishItemReturns> {
  return client.queryRequiredSingle(`\
insert Item {
  key := <str>$key,
  category := "fish",
}`, args);

}
