// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type GetRunnerKeyByInviteCodeArgs = {
  "code": string;
};

export type GetRunnerKeyByInviteCodeReturns = {
  "key": string;
} | null;

export async function getRunnerKeyByInviteCode(client: Executor, args: GetRunnerKeyByInviteCodeArgs): Promise<GetRunnerKeyByInviteCodeReturns> {
  return client.querySingle(`\
select InviteCode {
  key := .user.key
} filter .code = <uuid>$code`, args);

}
