// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type UseInviteCodeArgs = {
  "code": string;
  "identity": string;
};

export type UseInviteCodeReturns = {
  "id": string;
} | null;

export async function useInviteCode(client: Executor, args: UseInviteCodeArgs): Promise<UseInviteCodeReturns> {
  return client.querySingle(`\
with inviteCode := (
  select InviteCode
  filter .code = <uuid>$code
),
user := inviteCode.user,
identity := (
  select ext::auth::Identity 
  filter .id = <uuid>$identity
),
_delete_invite_code := (delete inviteCode)
update user
set {
  identity := identity,
}`, args);

}
