// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type UpdateSheetsArgs = {
  "data": unknown;
};

export type UpdateSheetsReturns = {
  "id": string;
}[];

export async function updateSheets(client: Executor, args: UpdateSheetsArgs): Promise<UpdateSheetsReturns> {
  return client.query(`\
for item in json_array_unpack(<json>$data) union (
  insert StaticData {
    sheet := <str>item["sheet"],
    data := <str>item["data"],
  }
  unless conflict on .sheet
  else (
    update StaticData
    set {
      data := <str>item["data"],
    }
  )
)`, args);

}
